version: '3.6'

networks:
  test:

services:
  postgresql:
    image: postgres:latest
    restart: always
    networks:
      - 'test'
    volumes:
      - './postgresql/:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    networks:
      - 'test'
    ports:
      - '8000:8000'
    environment:
      IP: 0.0.0.0
      PORT: 8000
      POSTGRES_PASSWORD: 1234
      POSTGRES_URL: postgresql
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/', '||', 'exit', '1']
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - 'postgresql'
